sudo: false

git:
  depth: 10

branches:
  only:
    - master

language: node_js

cache: yarn

matrix:
  include:
    - node_js: '11'
      script: yarn pretest
      env: CI=pretest
    - node_js: '6'
      script: yarn test:ci
      env: CI=tests 6
    - node_js: '8'
      script: yarn test:ci
      env: CI=tests 8
    - node_js: '10'
      script: yarn test:ci
      env: CI=tests 10
    - node_js: '11'
      script: yarn test:ci
      env: CI=coverage 11

before_install:
  - yarn install --ignore-engines

after_success:
  - if [ "$CI" = "coverage" ]; then cat ./.coverage/lcov.info | ./node_modules/.bin/coveralls --verbose && rm -rf ./coverage; fi
