sudo: false
language: node_js
node_js:
  - "4"
script: npm run travis

before_install:
  - 'npm install -g npm'

after_success: cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose && rm -rf ./coverage
